version: "3"
services:
  spring-test:
    image: spring-boot-test
    ports:
      - "8080:8080"
    networks:
      - spring-network-test
    depends_on:
      - mysqldb
 
  mysqldb:
    image: mysql:8
    networks:
      - spring-network-test
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=bootdb  

networks:
  spring-network-test:
