# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ main ]
    paths: [ '**.java' ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - uses: avinal/github-pages-deploy-action@main
      with:
        # GitHub access token with Repo Access
        GITHUB_TOKEN: ${{ github.token }}
        # For JavaDoc - "java"
        # For python write python package and additional packages if any - "python3 python3-pip" 
        LANGUAGE: "java"
        # Write make command to generate html e.g.- "make html"
        MAKE_COMMAND: "./gradlew clean build javadoc"
        # Write the branch name for storing github pages source 
        PAGES_BRANCH: "gh-pages"
        # Write the branch name having source files for site/documentation
        BUILD_FROM: "main"
        # Write the name of the output folder where generated html is stored by makefile.
        DOCS_FOLDER: "build/docs/javadoc"
